### ISSUE TITLE
No styling for `hr` makes them invisible

### ISSUE THREAD

**Issue by askoufis** [Everblush/Obsidian#1]
`hr` tags aren't visible with the recent theme updates.

Adding something like this to the theme css has been my workaround, but would be great to have a fix upstream.

```css
.markdown-preview-view hr {
    border: none;
    border-top: 1px solid var(--text-faint);
}

.markdown-source-view hr {
    border: none;
    border-top: 1px solid var(--text-faint);
}
```
